### ISSUE TITLE
Syntax Highlight breaks with question mark

### ISSUE THREAD

**Issue by wlingke** [orktes/atom-react#212]
![image](https://cloud.githubusercontent.com/assets/3145536/20295962/0abc580e-aabd-11e6-8ffe-4404481e64f5.png)

**Comment by neuling** [comment]
+1

**Comment by tommg** [comment]
+1 here too

**Comment by krazi3** [comment]
+1

**Comment by aforty** [comment]
Same here. Any movement on this?

**Comment by aforty** [comment]
Also really terrible work-around for the desperate.

```jsx
<label>A sentence with a question mark{'?'}</label>
```

**Comment by basistam** [comment]
+1

**Comment by mmbmatteo** [comment]
Single quote also breaks it really bad

![screen shot 2016-12-19 at 18 12 33](https://cloud.githubusercontent.com/assets/16538746/21321855/e383f452-c616-11e6-9e82-9a8072296ac0.png)

**Comment by neocoder** [comment]
@mmbmatteo I think, in this case single quote breaks it even worse because of improper question mark handling in the first place. I just tried the fix on the code similar to yours and everything works fine. I pushed the needed test so I hope @orktes will make a merge soon.

**Comment by boldkhuu** [comment]
Question mark of the ternary operator causes this issue too.
![image](https://cloud.githubusercontent.com/assets/2161151/21490265/767c641c-cc2d-11e6-9cc3-2854555185c3.png)

**Comment by merlinpatt** [comment]
Has the fix been published?

**Comment by neocoder** [comment]
@merlinpatt The fix is released with  0.16.2

**Comment by winterblack** [comment]
I'm still having this problem with both 1.16.0 and 1.17.0-beta3

**Comment by neocoder** [comment]
@winterblack It was a bug of atom-react package, not the atom itself. I'm on atom 1.16.0 and atom-react 0.16.2 and everything works fine.

**Comment by venligboerne** [comment]
Check out [language-babel](https://atom.io/packages/language-babel)! It fixes a bunch of syntax highlighting issues like apostrophes and question marks and generally makes JSX easier to deal with.
